# Generated by Django 4.2.28 on 2026-02-20 07:01

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Адрес страницы, например: skupka-noutbukov', max_length=200, unique=True, verbose_name='URL')),
                ('page_type', models.CharField(choices=[('home', 'Главная страница'), ('skupka', 'Страница скупки'), ('remont', 'Страница ремонта'), ('info', 'Информационная страница')], default='info', max_length=20, verbose_name='Тип страницы')),
                ('hero_title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок в hero-секции')),
                ('hero_subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок в hero-секции')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Основной контент')),
                ('advantages_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока преимуществ')),
                ('advantage_1_title', models.CharField(blank=True, max_length=100, verbose_name='Преимущество 1 - заголовок')),
                ('advantage_1_text', models.CharField(blank=True, max_length=200, verbose_name='Преимущество 1 - текст')),
                ('advantage_2_title', models.CharField(blank=True, max_length=100, verbose_name='Преимущество 2 - заголовок')),
                ('advantage_2_text', models.CharField(blank=True, max_length=200, verbose_name='Преимущество 2 - текст')),
                ('advantage_3_title', models.CharField(blank=True, max_length=100, verbose_name='Преимущество 3 - заголовок')),
                ('advantage_3_text', models.CharField(blank=True, max_length=200, verbose_name='Преимущество 3 - текст')),
                ('advantage_4_title', models.CharField(blank=True, max_length=100, verbose_name='Преимущество 4 - заголовок')),
                ('advantage_4_text', models.CharField(blank=True, max_length=200, verbose_name='Преимущество 4 - текст')),
                ('advantage_5_title', models.CharField(blank=True, max_length=100, verbose_name='Преимущество 5 - заголовок')),
                ('advantage_5_text', models.CharField(blank=True, max_length=200, verbose_name='Преимущество 5 - текст')),
                ('show_contact_form', models.BooleanField(default=True, verbose_name='Показывать форму заявки')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('menu_title', models.CharField(blank=True, help_text='Если пусто, будет использован заголовок страницы', max_length=100, verbose_name='Название в меню')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в меню')),
                ('meta_title', models.CharField(blank=True, help_text='Если пусто, будет использован заголовок страницы', max_length=200, verbose_name='SEO: Title')),
                ('meta_description', models.TextField(blank=True, max_length=500, verbose_name='SEO: Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='SEO: Keywords')),
                ('og_image', models.ImageField(blank=True, upload_to='og_images/', verbose_name='SEO: OG Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Компьютеры?', max_length=200, verbose_name='Название сайта')),
                ('phone', models.CharField(default='8 (953) 921-15-72', max_length=50, verbose_name='Телефон')),
                ('phone_link', models.CharField(default='+79539211572', max_length=20, verbose_name='Телефон для ссылки')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='г.Томск, ул. Советская, д. 90', max_length=300, verbose_name='Адрес')),
                ('working_hours', models.CharField(default='Ежедневно с 10:00 до 20:00', max_length=100, verbose_name='Часы работы')),
                ('whatsapp_link', models.URLField(blank=True, verbose_name='Ссылка на WhatsApp')),
                ('years_work', models.PositiveIntegerField(default=10, verbose_name='Лет работы')),
                ('devices_bought', models.PositiveIntegerField(default=1580, verbose_name='Купленных устройств')),
                ('devices_sold', models.PositiveIntegerField(default=1705, verbose_name='Проданных устройств')),
                ('happy_clients', models.PositiveIntegerField(default=3285, verbose_name='Довольных клиентов')),
                ('devices_repaired', models.PositiveIntegerField(default=1287, verbose_name='Отремонтированных устройств')),
                ('footer_text', models.TextField(blank=True, verbose_name='Текст в футере')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('device_info', models.TextField(blank=True, help_text='Модель, состояние и т.д.', verbose_name='Информация об устройстве')),
                ('page_url', models.CharField(blank=True, max_length=200, verbose_name='URL страницы')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
