# Generated by Django 4.2.28 on 2026-02-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_code',
            field=models.TextField(blank=True, help_text='Вставьте код iframe с Яндекс.Карт или Google Maps', verbose_name='Код карты (iframe)'),
        ),
    ]
