# Generated by Django 4.2.28 on 2026-02-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_map_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Токен бота от @BotFather (например: 123456789:ABCdefGHIjklMNOpqrsTUVwxyz)', max_length=100, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID группы или чата для отправки заявок (например: -1001234567890)', max_length=50, verbose_name='Telegram Chat ID'),
        ),
    ]
