# Generated by Django 4.2.28 on 2026-02-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='recaptcha_min_score',
            field=models.FloatField(default=0.5, help_text='От 0.0 до 1.0. Рекомендуется 0.5. Чем выше - тем строже проверка', verbose_name='Минимальный score reCAPTCHA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='recaptcha_secret_key',
            field=models.CharField(blank=True, help_text='Секретный ключ reCAPTCHA v3', max_length=100, verbose_name='reCAPTCHA Secret Key'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='recaptcha_site_key',
            field=models.CharField(blank=True, help_text='Публичный ключ reCAPTCHA v3 (получить на google.com/recaptcha)', max_length=100, verbose_name='reCAPTCHA Site Key'),
        ),
    ]
