# Generated by Django 4.2.28 on 2026-02-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_recaptcha_min_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_link',
            field=models.URLField(blank=True, help_text='Например: https://t.me/username', verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='Например: https://wa.me/79539211572', verbose_name='Ссылка на WhatsApp'),
        ),
    ]
