# Generated by Django 4.2.28 on 2026-02-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_telegram_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTelegramMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_normalized', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Телефон (нормализованный)')),
                ('telegram_chat_id', models.CharField(max_length=50, verbose_name='Telegram Chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Телефон → Telegram',
                'verbose_name_plural': 'Телефоны в Telegram',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_client_message',
            field=models.TextField(blank=True, default='Для более точной оценки приходите в наш офис на Советской 90. Либо отправьте фото внешнего вида и характеристик в чат +7 952 182 8284', help_text='Отправляется клиенту в Telegram, если его телефон найден (он ранее отправил контакт боту)', verbose_name='Сообщение клиенту в Telegram'),
        ),
    ]
