# Generated by Django 4.2.28 on 2026-02-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_telegram_client_mapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactTelegramMapping',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='telegram_client_message',
        ),
    ]
