# Generated by Django 4.2.28 on 2026-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_telegram_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_metrika',
            field=models.TextField(blank=True, help_text='Вставьте полный код счётчика из личного кабинета Метрики (скрипт целиком)', verbose_name='Код счётчика Яндекс.Метрики'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_verification',
            field=models.CharField(blank=True, help_text='Значение content из тега <meta name="yandex-verification" content="..."> (только значение, без кавычек)', max_length=100, verbose_name='Код верификации Яндекс.Вебмастер'),
        ),
    ]
